/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 投递列表 */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /** 记录投递 */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除投递 */
        delete: operations["delete_application_api_applications__application_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 推进投递阶段 */
        post: operations["update_stage_api_applications__application_id__stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话列表 */
        get: operations["list_conversations_api_assistant_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话消息 */
        get: operations["conversation_messages_api_assistant_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 流式对话（SSE） */
        post: operations["stream_api_assistant_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 跑一轮对话（一次性返回） */
        post: operations["turn_api_assistant_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启动一轮抓取 */
        post: operations["start_crawl_api_crawl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 抓取进度快照 */
        get: operations["crawl_status_api_crawl_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 岗位列表（搜索+分页） */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 岗位详情（全 id 或唯一前缀） */
        get: operations["job_detail_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读候选人画像（未配置时为 null） */
        get: operations["read_profile_api_scoring_profile_get"];
        /** 保存候选人画像 */
        put: operations["save_profile_api_scoring_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 给一个岗位评分并写回 */
        post: operations["score_api_scoring__job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取 LLM 配置 */
        get: operations["read_settings_api_settings_get"];
        /** 保存 LLM 配置 */
        put: operations["save_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 连通性探测（真发一次最小请求） */
        post: operations["test_connection_api_settings_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApplicationListResponse
         * @description 投递列表页。
         *
         *     `total` / `has_more` 是**截断信号**：列表有固定上限（见 router 的 `LIST_LIMIT`），
         *     没有它们时第 201 条起永久不可见、且界面看起来「这就是全部」。
         */
        ApplicationListResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["ApplicationSummary"][];
            /** Total */
            total: number;
        };
        /**
         * ApplicationStage
         * @description 投递所处阶段。顺序即流程顺序，界面按此排进度。
         * @enum {string}
         */
        ApplicationStage: "applied" | "written_test" | "interview" | "offer" | "rejected" | "withdrawn";
        /**
         * ApplicationSummary
         * @description 投递列表项。
         */
        ApplicationSummary: {
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Company */
            company: string;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Note */
            note?: string | null;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApplyResponse
         * @description 记录投递的结果。
         */
        ApplyResponse: {
            /** Application Id */
            application_id: string;
        };
        /**
         * CandidateProfile
         * @description 候选人画像。至少要有一项信号，否则评分无从谈起。
         */
        CandidateProfile: {
            /** Directions */
            directions?: string[];
            /** Keywords */
            keywords?: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * ConnectionTestResponse
         * @description 连通性探测的结果 —— **有类型的响应**，不是裸 dict。
         *
         *     裸 `dict[str, str]` 会让 OpenAPI 退化成 `additionalProperties: {type: string}`
         *     （契约里看不出有什么字段），前端只能靠魔法值判断：`probe.data.ok === "1"`。
         *     本仓库其余 5 个切片所有端点都有类型，唯独这里漏了（AGENTS.md「响应要有类型」）。
         *
         *     `ok` 用 **bool** 而不是 "1"/"0"：字符串状态码有两个毛病 —— 前端得写
         *     `=== "1"` 这种依赖约定的比较；契约里也说不清 `ok` 到底有哪些取值。
         */
        ConnectionTestResponse: {
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * ConversationMessageView
         * @description 会话里的一条消息。
         */
        ConversationMessageView: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /**
         * ConversationSummary
         * @description 会话列表项。
         */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CrawlStatusResponse
         * @description 抓取进度快照。
         */
        CrawlStatusResponse: {
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Running */
            running: boolean;
            /** Sites */
            sites: components["schemas"]["SiteProgressView"][];
            /** Started At */
            started_at?: string | null;
            /** Total Created */
            total_created: number;
            /** Total Fetched */
            total_fetched: number;
        };
        /**
         * CreateApplicationRequest
         * @description 记录一次投递的请求体。
         *
         *     `job_id` 支持全 id 或唯一前缀（与岗位详情端点同一套解析）—— 助手常只看到
         *     前 8 位 id，界面给的是全 id，两者都得能用。
         */
        CreateApplicationRequest: {
            /** Job Id */
            job_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetail
         * @description 岗位详情（列表项 + JD 正文）。
         */
        JobDetail: {
            /** Capture Status */
            capture_status: string;
            /** City */
            city?: string | null;
            /** Company */
            company: string;
            /** Detail Url */
            detail_url: string;
            /** Id */
            id: string;
            /** Jd Raw */
            jd_raw?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * JobListResponse
         * @description 岗位列表页（搜索 + 分页）。
         */
        JobListResponse: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["JobSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * JobSummary
         * @description 岗位列表项。
         */
        JobSummary: {
            /** Capture Status */
            capture_status: string;
            /** City */
            city?: string | null;
            /** Company */
            company: string;
            /** Detail Url */
            detail_url: string;
            /** Id */
            id: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Match Score */
            match_score?: number | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
        };
        /**
         * ProfileForm
         * @description `PUT /api/scoring/profile` 的请求体。
         */
        ProfileForm: {
            /** Directions */
            directions?: string[];
            /** Keywords */
            keywords?: string[];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * ProfileView
         * @description `GET` / `PUT /api/scoring/profile` 的响应。
         *
         *     「没配过」用 `profile: null` 表达，而不是 404：未配置是**初始状态**，不是错误。
         *     界面据此渲染空表单。
         *
         *     `warning` 用于「存储里的画像不合法」（例如按旧规则存下的超大画像，或数据被
         *     改坏）：此时 `profile` 给 `null` **并**说明原因 —— 既不让用户撞上 500 而无法
         *     打开配置页去修，也不静默假装没配过（那会掩盖损坏、让用户填过的内容无声消失）。
         */
        ProfileView: {
            profile?: components["schemas"]["CandidateProfile"] | null;
            /** Warning */
            warning?: string | null;
        };
        /**
         * ScoreView
         * @description `POST /api/scoring/{job_id}` 的响应。
         */
        ScoreView: {
            /** Job Id */
            job_id: string;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Score */
            score: number;
            /** Summary */
            summary?: string | null;
        };
        /**
         * SettingsForm
         * @description 配置页提交的表单。`api_key` 留空表示「不改」。
         */
        SettingsForm: {
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
        };
        /**
         * SettingsView
         * @description 回给界面的配置（密钥只给掩码）。
         *
         *     字段都带默认值，是为了容纳**配置已损坏**这一形状：此时没有任何可信值可回显，
         *     给一组空值 + `broken=True`，让表单直接空白可填（用户重填即可自救）。
         *     正常路径由 `_view()` 唯一构造，字段一定齐全。
         */
        SettingsView: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Broken
             * @default false
             */
            broken: boolean;
            /**
             * Configured
             * @default false
             */
            configured: boolean;
            /**
             * Masked Key
             * @default
             */
            masked_key: string;
            /**
             * Model
             * @default
             */
            model: string;
            /** Warning */
            warning?: string | null;
        };
        /**
         * SiteProgressView
         * @description 一个站点在这一轮里的进度。
         */
        SiteProgressView: {
            /** Created */
            created: number;
            /** Error */
            error?: string | null;
            /** Fetched */
            fetched: number;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Updated */
            updated: number;
        };
        /**
         * StageUpdateRequest
         * @description 推进投递阶段的请求体。
         *
         *     `stage` 直接用 `ApplicationStage` 而非 `str`：OpenAPI 快照里会输出**真正的
         *     enum**（前端可照契约比对，不再靠魔法字符串对齐一份手抄的取值表），非法值由
         *     请求体校验直接拒为 422 —— 路由不必再手工判一次、也就不会漏判。
         */
        StageUpdateRequest: {
            /** Note */
            note?: string | null;
            stage: components["schemas"]["ApplicationStage"];
        };
        /**
         * StageUpdateResponse
         * @description 推进投递阶段的结果。
         */
        StageUpdateResponse: {
            /** Application Id */
            application_id: string;
            /** Stage */
            stage: string;
        };
        /**
         * StartCrawlResponse
         * @description 启动结果。`started=False` 表示上一轮还在跑（不是错误）。
         */
        StartCrawlResponse: {
            /** Started */
            started: boolean;
        };
        /**
         * StreamRequest
         * @description 对话请求体（流式与一次性共用）。
         */
        StreamRequest: {
            /**
             * Conversation Id
             * @default
             */
            conversation_id: string;
            /** Message */
            message: string;
        };
        /**
         * TurnResponse
         * @description 一次性对话的结果。
         */
        TurnResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Iterations */
            iterations: number;
            /** Reply */
            reply: string;
            /** Truncated */
            truncated: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_applications_api_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description 该岗位已有投递记录（幂等命中）—— 返回既有记录的 id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stage_api_applications__application_id__stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_assistant_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
        };
    };
    conversation_messages_api_assistant_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationMessageView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_assistant_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turn_api_assistant_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_crawl_api_crawl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCrawlResponse"];
                };
            };
        };
    };
    crawl_status_api_crawl_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlStatusResponse"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description 关键词（标题归一化匹配；空 = 列最近） */
                q?: string;
                /** @description 页码（1 起，上限 10000） */
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_detail_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_api_scoring_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
        };
    };
    save_profile_api_scoring_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_api_scoring__job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"] | null;
                };
            };
        };
    };
    save_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_settings_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
        };
    };
}
